sudo: required
cache: bundler
services:
  - docker
env:
  global:
    - COMPOSE_FILE: docker-compose.ci.yml
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
install:
  - docker-compose build --build-arg TARGET_VERSION=$TARGET_VERSION
script:
  - docker-compose run ci
matrix:
  include:
    - name: 2.5.8
      env: TARGET_VERSION=2.5.8
    - name: 2.6.6
      env: TARGET_VERSION=2.6.6
    - name: 2.7.1
      env: TARGET_VERSION=2.7.1
