image: Visual Studio 2017
skip_tags: true
clone_depth: 5
build: off
matrix:
  fast_finish: true
  allow_failures:
    - ruby_version: "25"
    - ruby_version: "26"
    - ruby_version: "27"
    - ruby_version: "27-x64"
services:
  - mssql2014

init:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - SET PATH=C:\MinGW\msys\1.0\bin;%PATH%
  - SET RAKEOPT=-rdevkit
  - SET TINYTDS_VERSION=2.1.3.pre

install:
  - ps: Update-AppveyorBuild -Version "$(Get-Content $env:appveyor_build_folder\VERSION).$env:appveyor_build_number"
  - ruby --version
  - gem --version
  - bundle install
  - gem uninstall bcrypt
  - gem install bcrypt --platform=ruby

test_script:
  - powershell -File "%APPVEYOR_BUILD_FOLDER%\test\appveyor\dbsetup.ps1"
  - timeout /t 4 /nobreak > NUL
  - sqlcmd -S ".\SQL2014" -U sa -P Password12! -i %APPVEYOR_BUILD_FOLDER%\test\appveyor\dbsetup.sql
  - bundle exec rake test ACTIVERECORD_UNITTEST_DATASERVER="localhost\SQL2014"

environment:
  CI_AZURE_HOST:
    secure: VChrioaIWkf9iuuaSs4cryiA4honrADgZqNC0++begg=
  CI_AZURE_PASS:
    secure: cSQp8sk4urJYvq0utpsK+r7J+snJ2wpcdp8RdXJfB+w=
  matrix:
    - ruby_version: "25-x64"
    - ruby_version: "25"
    - ruby_version: "26-x64"
    - ruby_version: "26"
    - ruby_version: "27-x64"
    - ruby_version: "27"
