init:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - SET PATH=C:\MinGW\msys\1.0\bin;%PATH%
  - SET RAKEOPT=-rdevkit
  - SET TINYTDS_VERSION=2.1.0
clone_depth: 5
skip_tags: true
matrix:
  fast_finish: true
install:
  - ps: Update-AppveyorBuild -Version "$(Get-Content $env:appveyor_build_folder\VERSION).$env:appveyor_build_number"
  - ruby --version
  - gem --version
  - bundle install
  - gem uninstall bcrypt
  - gem install bcrypt --platform=ruby
build: off
test_script:
  - powershell -File "%APPVEYOR_BUILD_FOLDER%\test\appveyor\dbsetup.ps1"
  - timeout /t 4 /nobreak > NUL
  - ps: Start-Service 'MSSQL$SQL2014'
  - timeout /t 4 /nobreak > NUL
  - sqlcmd -S ".\SQL2014" -U sa -P Password12! -i %APPVEYOR_BUILD_FOLDER%\test\appveyor\dbsetup.sql
  - bundle exec rake test ACTIVERECORD_UNITTEST_DATASERVER="localhost\SQL2014"
  - ps: Stop-Service 'MSSQL$SQL2014'
  - ps: Start-Service 'MSSQL$SQL2012SP1'
  - timeout /t 4 /nobreak > NUL
  - sqlcmd -S ".\SQL2012SP1" -U sa -P Password12! -i %APPVEYOR_BUILD_FOLDER%\test\appveyor\dbsetup.sql
  - bundle exec rake test ACTIVERECORD_UNITTEST_DATASERVER="localhost\SQL2012SP1"
environment:
  CI_AZURE_HOST:
    secure: VChrioaIWkf9iuuaSs4cryiA4honrADgZqNC0++begg=
  CI_AZURE_PASS:
    secure: cSQp8sk4urJYvq0utpsK+r7J+snJ2wpcdp8RdXJfB+w=
  matrix:
    - ruby_version: "23-x64"
    - ruby_version: "23"
    - ruby_version: "22-x64"
    - ruby_version: "22"
