init:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - SET PATH=C:\MinGW\msys\1.0\bin;%PATH%
  - SET RAKEOPT=-rdevkit
  - SET TINYTDS_VERSION=0.9.5.rc.1
clone_depth: 5
skip_tags: true
matrix:
  fast_finish: true
install:
  - ps: Update-AppveyorBuild -Version "$(Get-Content $env:appveyor_build_folder\VERSION).$env:appveyor_build_number"
  - ruby --version
  - gem --version
  - bundle install --without odbc
build: off
test_script:
  - bundle exec rake test ACTIVERECORD_UNITTEST_AZURE=1 ACTIVERECORD_UNITTEST_HOST=%CI_AZURE_HOST% ACTIVERECORD_UNITTEST_PASS=%CI_AZURE_PASS%
environment:
  CI_AZURE_HOST:
    secure: VChrioaIWkf9iuuaSs4cryiA4honrADgZqNC0++begg=
  CI_AZURE_PASS:
    secure: cSQp8sk4urJYvq0utpsK+r7J+snJ2wpcdp8RdXJfB+w=
  matrix:
    - ruby_version: "22-x64"
